name: fancy_todo
description: A fancy TODO app for demo
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add this line to use environment variables
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
